{% set version = "2.0.12" %}

package:
  name: nr
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nr/nr-{{ version }}.tar.gz
  sha256: 9d21cece3deebd8cd4aa7f865d7c6dde17596f330e305d4850ae00a561a64692

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - nr

about:
  home: https://github.com/NiklasRosenstein/py-nr
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'collection of programming utilities'

extra:
  recipe-maintainers:
    - dfroger
