appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: vBY3EdNb5FgT7Xz1Dc8752PIOGg+ki2g7Cw/g5SSh3qgyQAYlAT+mdt9WL9R9PlK3MtSC2+jw3E1NS/EnR2ZrWgPEDyE4NhVgcqoVSuilWA7YBp1cXbFAJM2ANNzHFQquuR4kNG0K7EF9htDC5a8Np0JHFUqaauT8bBMu3nrFBBrLGI69nueVOMn4bGhh81JZ8yR0xIkyKMur99tPz8Zo4H6SaN8TfnYhQDkS1tAbsrKaCTzEgfxXKjk2mqB6TwrC2K5hnXN0BAkK1hUTt9oYKzhMCVXnMBgQjT3nyMA3EJxyvTUmGErNfS2PLNo57eTr/GXWDcPLDO1ZSneh+DvxtZGd0VA8mKKSTs0GHlPEyFIZgTTWUgMPsVbPmqiCrASOklN0qPKfLbg0urUAwTMdFjLbMeROP4BK0KKmiFV/3NzcdvhsbhnrgYHyXuTOXHrWQA3Dn14A/ZVZtNMQsATuWaFVgAYqMYQ3XPQE3qrVk8OWTrH1280KlB0i3EupFRtA2QSMkU9LvdD+ezWvkQ0TAxnY+1ICcxI0Vb5mVCcLLTIWXq9rmUfT86/QEEKjTg3oWKhj7s1ak+ilp2UcGtAk/91OMmlWuNbounEY0f3Bq+FNAS35PjsDzZuJfzkZJ+Ue79c1zxesBZUb11XqO8Y9C9b9/dSh9t4DMwaeu71rT0=}
